const memoryPalaceObjects = [
    // Common household items
    "Apple", "Banana", "Car", "Dog", "Elephant", "Flower", "Guitar", "House", "Ice Cream", "Jacket",
    "Kite", "Lamp", "Mountain", "Notebook", "Orange", "Piano", "Queen", "Robot", "Sun", "Tree",
    "Umbrella", "Violin", "Whale", "Xylophone", "Yacht", "Zebra", "Book", "Chair", "Door", "Egg",
    "Fan", "Glass", "Hat", "Iron", "Jar", "Key", "Lion", "Mirror", "Nail", "Owl",
    "Pen", "Quilt", "Ring", "Shoe", "Table", "Urn", "Vase", "Watch", "X-ray", "Yarn",
    "Sofa", "Couch", "Rug", "Carpet", "Bookshelf", "Clock", "Painting", "Poster", "Plant", "Candle",
    "Towel", "Soap", "Shampoo", "Toothbrush", "Toothpaste", "Broom", "Mop", "Bucket", "Sponge", "Gloves",
    "Desk", "Bed", "Pillow", "Blanket", "Duvet", "Wardrobe", "Hanger", "Dresser", "Nightstand", "Alarm Clock",
    "Remote", "Lightbulb", "Switch", "Outlet", "Extension Cord", "Flashlight", "Lighter", "Matches", "Fire Extinguisher", "First Aid Kit",
    "Medicine", "Bandage", "Scissors", "Tape", "Glue", "Stapler", "Paper", "Envelope", "Stamp", "Calendar",
    "Diary", "Wallet", "Purse", "Backpack", "Suitcase", "Sunglasses", "Reading Glasses", "Magnifying Glass", "Binoculars", "Telescope",
    "Globe", "Map", "Atlas", "Compass", "Protractor", "Ruler", "Abacus", "Dice", "Playing Cards", "Chessboard",
    "Puzzle", "Toy", "Doll", "Action Figure", "Lego", "Ball", "Helmet", "Kneepads", "Elbowpads", "Jumprope",
    "Frisbee", "Boomerang", "Hula Hoop", "Trampoline", "Swing", "Slide", "Sandbox", "Pool", "Barbecue", "Grill",
    "Lawnmower", "Hose", "Sprinkler", "Shovel", "Rake", "Wheelbarrow", "Flowerpot", "Watering Can", "Garden Gnome", "Bird Feeder",
    "Mailbox", "Fence", "Gate", "Driveway", "Garage", "Attic", "Basement", "Roof", "Chimney", "Window",
    "Balcony", "Porch", "Stairs", "Elevator", "Hallway", "Room", "Ceiling", "Floor", "Wall", "Carpet",
    "Thermostat", "Radiator", "Fireplace", "Mantel", "Hearth", "Chandelier", "Sconce", "Dimmer", "Doorknob", "Keyhole",
    "Peephole", "Doorbell", "Doormat", "Coat Rack", "Shoe Rack", "Books", "Magazine", "Newspaper", "Bonsai", "Terrarium",
    
    // Animals
    "Cat", "Bird", "Fish", "Horse", "Cow", "Pig", "Sheep", "Goat", "Duck", "Chicken",
    "Bear", "Wolf", "Fox", "Deer", "Rabbit", "Squirrel", "Mouse", "Rat", "Hamster", "Guinea Pig",
    "Tiger", "Leopard", "Cheetah", "Jaguar", "Panther", "Lynx", "Bobcat", "Cougar", "Ocelot", "Serval",
    "Monkey", "Gorilla", "Chimpanzee", "Orangutan", "Baboon", "Lemur", "Sloth", "Koala", "Panda", "Kangaroo",
    "Crocodile", "Alligator", "Snake", "Lizard", "Turtle", "Frog", "Toad", "Salamander", "Newt", "Iguana",
    "Giraffe", "Rhinoceros", "Hippopotamus", "Hyena", "Warthog", "Meerkat", "Bat", "Otter", "Beaver", "Raccoon",
    "Skunk", "Badger", "Weasel", "Mink", "Ferret", "Mole", "Hedgehog", "Porcupine", "Armadillo", "Anteater",
    "Tapir", "Capybara", "Llama", "Alpaca", "Vicuna", "Guanaco", "Camel", "Dromedary", "Bison", "Buffalo",
    "Yak", "Moose", "Elk", "Reindeer", "Caribou", "Antelope", "Gazelle", "Impala", "Wildebeest", "Kudu",
    "Eland", "Oryx", "Springbok", "Gemsbok", "Hartebeest", "Topi", "Waterbuck", "Seal", "Sea Lion", "Walrus",
    "Dolphin", "Porpoise", "Shark", "Ray", "Stingray", "Eel", "Octopus", "Squid", "Cuttlefish", "Jellyfish",
    "Starfish", "Sea Urchin", "Sea Cucumber", "Crab", "Lobster", "Shrimp", "Crayfish", "Krill", "Barnacle", "Clam",
    "Oyster", "Mussel", "Scallop", "Snail", "Slug", "Worm", "Insect", "Bee", "Wasp", "Ant",
    "Beetle", "Butterfly", "Moth", "Dragonfly", "Grasshopper", "Cricket", "Cockroach", "Fly", "Mosquito", "Flea",
    "Louse", "Tick", "Spider", "Scorpion", "Centipede", "Millipede", "Eagle", "Hawk", "Falcon", "Vulture",
    "Condor", "Crow", "Raven", "Magpie", "Jay", "Pigeon", "Dove", "Sparrow", "Finch", "Canary",
    "Parrot", "Macaw", "Cockatoo", "Toucan", "Hummingbird", "Woodpecker", "Kingfisher", "Heron", "Stork", "Crane",
    "Flamingo", "Swan", "Goose", "Pelican", "Penguin", "Ostrich", "Emu", "Cassowary", "Kiwi", "Roadrunner",
    "Quail", "Pheasant", "Turkey", "Peacock", "Guinea Fowl", "Cobra", "Viper", "Python", "Boa", "Anaconda",
    
    // Food items
    "Pizza", "Burger", "Sandwich", "Salad", "Soup", "Pasta", "Rice", "Bread", "Cheese", "Milk",
    "Yogurt", "Butter", "Honey", "Sugar", "Salt", "Pepper", "Garlic", "Onion", "Tomato", "Potato",
    "Carrot", "Broccoli", "Spinach", "Lettuce", "Cucumber", "Bell Pepper", "Corn", "Peas", "Beans", "Lentils",
    "Strawberry", "Blueberry", "Raspberry", "Blackberry", "Grape", "Cherry", "Peach", "Pear", "Plum", "Apricot",
    "Watermelon", "Cantaloupe", "Honeydew", "Pineapple", "Mango", "Papaya", "Kiwi", "Coconut", "Avocado", "Lemon",
    "Lime", "Orange", "Grapefruit", "Tangerine", "Nectarine", "Fig", "Date", "Pomegranate", "Guava", "Passion Fruit",
    "Lychee", "Rambutan", "Dragon Fruit", "Star Fruit", "Jackfruit", "Durian", "Artichoke", "Asparagus", "Beetroot", "Cabbage",
    "Cauliflower", "Celery", "Eggplant", "Kale", "Leek", "Mushroom", "Okra", "Parsnip", "Pumpkin", "Radish",
    "Sweet Potato", "Turnip", "Zucchini", "Cilantro", "Basil", "Parsley", "Rosemary", "Thyme", "Oregano", "Mint",
    "Dill", "Sage", "Chives", "Tarragon", "Marjoram", "Cinnamon", "Nutmeg", "Clove", "Ginger", "Turmeric",
    "Cumin", "Coriander", "Cardamom", "Paprika", "Cayenne Pepper", "Chili Powder", "Mustard", "Ketchup", "Mayonnaise", "Vinegar",
    "Olive Oil", "Soy Sauce", "Hot Sauce", "Salsa", "Guacamole", "Hummus", "Tahini", "Pesto", "Jam", "Jelly",
    "Marmalade", "Peanut Butter", "Almond Butter", "Cashew Butter", "Maple Syrup", "Agave Nectar", "Chocolate", "Vanilla", "Caramel", "Toffee",
    "Fudge", "Ice Cream", "Sorbet", "Gelato", "Pudding", "Custard", "Mousse", "Cake", "Cupcake", "Cookie",
    "Brownie", "Pie", "Tart", "Pastry", "Donut", "Muffin", "Croissant", "Bagel", "Waffle", "Pancake",
    "Crepe", "Oats", "Granola", "Cereal", "Quinoa", "Couscous", "Barley", "Rye", "Spelt", "Flour",
    "Yeast", "Baking Soda", "Baking Powder", "Cornstarch", "Eggs", "Tofu", "Tempeh", "Seitan", "Edamame", "Beef",
    "Pork", "Lamb", "Bacon", "Sausage", "Salami", "Ham", "Steak", "Chop", "Ribs", "Roast",
    "Salmon", "Tuna", "Cod", "Sardine", "Trout", "Mackerel", "Herring", "Haddock", "Halibut", "Anchovy",
    
    // Technology
    "Computer", "Laptop", "Phone", "Tablet", "Television", "Radio", "Camera", "Headphones", "Speaker", "Microphone",
    "Keyboard", "Mouse", "Monitor", "Printer", "Scanner", "Router", "Modem", "Cable", "Charger", "Battery",
    "Remote Control", "Game Controller", "Virtual Reality Headset", "Drone", "Robot Vacuum", "Smart Watch", "Fitness Tracker", "GPS", "Bluetooth Speaker", "Webcam",
    "E-reader", "Projector", "Smart Home Hub", "Smart Lightbulb", "Smart Plug", "Smart Thermostat", "Security Camera", "Video Doorbell", "Digital Assistant", "Answering Machine",
    "Fax Machine", "Photocopier", "Laminator", "Shredder", "USB Drive", "External Hard Drive", "SD Card", "Memory Card Reader", "Server", "Mainframe",
    "Supercomputer", "Quantum Computer", "Typewriter", "Telegraph", "Telephone", "Pager", "Walkie-talkie", "Satellite", "Space Shuttle", "International Space Station",
    "Hubble Telescope", "Mars Rover", "Particle Accelerator", "Nuclear Reactor", "Solar Panel", "Wind Turbine", "Hydroelectric Dam", "Geothermal Plant", "Electric Car", "Hybrid Car",
    "Self-driving Car", "Maglev Train", "Hyperloop", "Jetpack", "Hoverboard", "Segway", "3D Printer", "CNC Machine", "Laser Cutter", "Robotic Arm",
    "Exoskeleton", "Bionic Limb", "Pacemaker", "MRI Machine", "Ultrasound Machine", "EEG Machine", "ECG Machine", "Defibrillator", "Microscope", "Spectrometer",
    "Oscilloscope", "Voltmeter", "Ammeter", "Ohmmeter", "Geiger Counter", "Barometer", "Anemometer", "Hygrometer", "Thermometer", "Seismograph",
    "Doppler Radar", "Sonar", "Lidar", "RFID Chip", "NFC Tag", "QR Code", "Barcode", "Magnetic Stripe", "Smart Card", "Cryptocurrency",
    "Blockchain", "Artificial Intelligence", "Machine Learning", "Neural Network", "Algorithm", "Software", "Firmware", "Hardware", "Operating System", "Application",
    
    // Clothing
    "Shirt", "Pants", "Dress", "Skirt", "Jacket", "Coat", "Sweater", "Hoodie", "T-shirt", "Jeans",
    "Shorts", "Socks", "Underwear", "Bra", "Tie", "Scarf", "Gloves", "Mittens", "Belt", "Suspenders",
    "Pajamas", "Robe", "Slippers", "Boots", "Sneakers", "Sandals", "High Heels", "Flip Flops", "Clogs", "Loafers",
    "Blouse", "Tunic", "Cardigan", "Vest", "Blazer", "Tuxedo", "Suit", "Overalls", "Jumpsuit", "Romper",
    "Leggings", "Tights", "Stockings", "Kilt", "Sarong", "Poncho", "Shawl", "Cape", "Muffler", "Ascot",
    "Bow Tie", "Cufflinks", "Pocket Square", "Fedora", "Beanie", "Beret", "Cap", "Visor", "Headband", "Earmuffs",
    "Balaclava", "Gaiter", "Bandana", "Arm Warmers", "Leg Warmers", "Garters", "Corset", "Bustier", "Lingerie", "Nightgown",
    "Swimsuit", "Bikini", "Trunks", "Wetsuit", "Drysuit", "Rash Guard", "Sun Hat", "Goggles", "Swim Cap", "Nose Clip",
    "Ear Plugs", "Fins", "Snorkel", "Life Jacket", "Apron", "Lab Coat", "Uniform", "Scrubs", "Chef Hat", "Hairnet",
    "Helmet", "Hard Hat", "Face Shield", "Safety Vest", "Steel-toed Boots", "Chaps", "Spats", "Gaiters", "Clogs", "Moccasins",
    "Espadrilles", "Wedges", "Pumps", "Stilettos", "Flats", "Oxfords", "Brogues", "Derbies", "Monk Straps", "Wingtips",
    
    // Sports & Recreation
    "Basketball", "Football", "Soccer Ball", "Tennis Ball", "Golf Ball", "Baseball", "Volleyball", "Ping Pong Ball", "Bowling Ball", "Pool Ball",
    "Racket", "Bat", "Club", "Paddle", "Stick", "Net", "Goal", "Hoop", "Target", "Dartboard",
    "Bicycle", "Skateboard", "Scooter", "Roller Skates", "Ice Skates", "Skis", "Snowboard", "Surfboard", "Kayak", "Canoe",
    "Frisbee", "Boomerang", "Hula Hoop", "Jumprope", "Kite", "Yo-yo", "Trampoline", "Swing Set", "Slide", "Seesaw",
    "Climbing Frame", "Monkey Bars", "Sandbox", "Paddling Pool", "Inflatable Raft", "Water Wings", "Pool Noodle", "Beach Ball", "Sun Lounger", "Parasol",
    "Cooler", "Picnic Basket", "Tent", "Sleeping Bag", "Camping Stove", "Lantern", "Compass", "Map", "Backpack", "Hiking Boots",
    "Trekking Poles", "Climbing Rope", "Harness", "Carabiner", "Chalk Bag", "Helmet", "Ice Axe", "Crampons", "Goggles", "Gloves",
    "Fishing Rod", "Reel", "Line", "Hook", "Bait", "Lure", "Tackle Box", "Net", "Waders", "Boat",
    "Archery Bow", "Arrow", "Quiver", "Target", "Fencing Foil", "Epee", "Sabre", "Mask", "Jacket", "Glove",
    "Boxing Gloves", "Punching Bag", "Headgear", "Mouthguard", "Hand Wraps", "Jump Rope", "Weight Bench", "Dumbbells", "Barbell", "Kettlebell",
    "Resistance Bands", "Yoga Mat", "Foam Roller", "Exercise Ball", "Treadmill", "Elliptical", "Stationary Bike", "Rowing Machine", "Stair Climber", "Pull-up Bar",
    
    // Musical Instruments
    "Drums", "Trumpet", "Saxophone", "Flute", "Clarinet", "Oboe", "Bassoon", "Tuba", "French Horn", "Trombone",
    "Harp", "Cello", "Viola", "Double Bass", "Mandolin", "Banjo", "Ukulele", "Harmonica", "Accordion", "Bagpipes",
    "Sitar", "Lute", "Zither", "Dulcimer", "Harpsichord", "Clavichord", "Organ", "Synthesizer", "Keyboard", "Keytar",
    "Theremin", "Ocarina", "Recorder", "Pan Flute", "Didgeridoo", "Kazoo", "Jew's Harp", "Melodica", "Concertina", "Bandoneon",
    "Gong", "Cymbal", "Tambourine", "Maracas", "Castanets", "Triangle", "Cowbell", "Wood Block", "Claves", "Guiro",
    "Vibraslap", "Flexatone", "Ratchet", "Sleigh Bells", "Chimes", "Glockenspiel", "Marimba", "Vibraphone", "Steel Drum", "Handpan",
    "Bongos", "Congas", "Djembe", "Cajon", "Tabla", "Bodhran", "Taiko", "Timpani", "Drum Machine", "Sampler",
    
    // Tools & Hardware
    "Hammer", "Screwdriver", "Wrench", "Pliers", "Saw", "Drill", "Level", "Measuring Tape", "Screws", "Nails",
    "Bolt", "Nut", "Washer", "Screw", "Anchor", "Wire", "Rope", "Chain", "Lock", "Hinge",
    "Paint Brush", "Roller", "Ladder", "Toolbox", "Work Bench", "Vise", "Clamp", "File", "Sandpaper", "Glue",
    "Adhesive", "Caulk", "Sealant", "Putty", "Spackle", "Grout", "Thinner", "Stripper", "Solvent", "Lubricant",
    "WD-40", "Duct Tape", "Masking Tape", "Electrical Tape", "Teflon Tape", "Zip Tie", "Cable Tie", "Bungee Cord", "Ratchet Strap", "Tarp",
    "Crowbar", "Pry Bar", "Mallet", "Sledgehammer", "Axe", "Hatchet", "Machete", "Pickaxe", "Shovel", "Spade",
    "Rake", "Hoe", "Trowel", "Cultivator", "Pruning Shears", "Loppers", "Hedge Trimmer", "Chainsaw", "Lawn Mower", "Weed Whacker",
    "Leaf Blower", "Pressure Washer", "Air Compressor", "Nail Gun", "Staple Gun", "Rivet Gun", "Soldering Iron", "Welder", "Angle Grinder", "Bench Grinder",
    "Jigsaw", "Circular Saw", "Miter Saw", "Table Saw", "Band Saw", "Router", "Sander", "Planer", "Jointer", "Lathe",
    "Drill Press", "Anvil", "Forge", "Bellows", "Tongs", "Chisel", "Gouge", "Awl", "Plane", "Spokeshave",
    "Caliper", "Micrometer", "Square", "Protractor", "Plumb Bob", "Chalk Line", "Stud Finder", "Voltage Tester", "Multimeter", "Continuity Tester",
    
    // Nature
    "Rock", "Stone", "Pebble", "Sand", "Dirt", "Mud", "Clay", "Grass", "Moss", "Fern",
    "Oak Tree", "Pine Tree", "Maple Tree", "Birch Tree", "Palm Tree", "Cactus", "Rose", "Tulip", "Sunflower", "Daisy",
    "River", "Lake", "Ocean", "Stream", "Waterfall", "Mountain", "Hill", "Valley", "Desert", "Forest",
    "Jungle", "Swamp", "Marsh", "Tundra", "Taiga", "Savanna", "Prairie", "Steppe", "Meadow", "Pasture",
    "Field", "Grove", "Orchard", "Vineyard", "Garden", "Lawn", "Hedge", "Bush", "Shrub", "Vine",
    "Creek", "Pond", "Lagoon", "Bay", "Gulf", "Sea", "Strait", "Channel", "Fjord", "Geyser",
    "Volcano", "Glacier", "Iceberg", "Avalanche", "Landslide", "Earthquake", "Tsunami", "Hurricane", "Tornado", "Cyclone",
    "Blizzard", "Hailstorm", "Thunderstorm", "Lightning", "Rainbow", "Aurora", "Sunrise", "Sunset", "Moonlight", "Starlight",
    "Constellation", "Galaxy", "Nebula", "Comet", "Meteor", "Asteroid", "Planet", "Star", "Sun", "Moon",
    "Cloud", "Fog", "Mist", "Haze", "Smog", "Rain", "Snow", "Sleet", "Hail", "Dew",
    "Frost", "Ice", "Puddle", "Island", "Peninsula", "Archipelago", "Continent", "Plateau", "Canyon", "Cave",
    "Stalactite", "Stalagmite", "Fossil", "Amber", "Coal", "Diamond", "Gold", "Silver", "Copper", "Iron",
    
    // Transportation
    "Airplane", "Helicopter", "Train", "Bus", "Truck", "Motorcycle", "Boat", "Ship", "Submarine", "Rocket",
    "Taxi", "Ambulance", "Fire Truck", "Police Car", "School Bus", "Delivery Van", "Pickup Truck", "SUV", "Convertible", "Limousine",
    "Minivan", "Hatchback", "Sedan", "Coupe", "Roadster", "Station Wagon", "RV", "Camper Van", "Motorhome", "Caravan",
    "Trailer", "Tractor", "Combine Harvester", "Forklift", "Bulldozer", "Excavator", "Crane", "Dump Truck", "Garbage Truck", "Tow Truck",
    "Streetcar", "Trolley", "Cable Car", "Monorail", "Maglev", "Funicular", "Gondola", "Chairlift", "Ski Lift", "T-bar",
    "Ferry", "Hovercraft", "Hydrofoil", "Yacht", "Catamaran", "Trimaran", "Sailboat", "Canoe", "Kayak", "Rowboat",
    "Jet Ski", "Speedboat", "Barge", "Tugboat", "Tanker", "Cargo Ship", "Cruise Ship", "Battleship", "Aircraft Carrier", "Destroyer",
    
    // Office Supplies
    "Stapler", "Paper Clips", "Rubber Bands", "Binder", "File Folder", "Calculator", "Ruler", "Scissors", "Tape", "Glue Stick",
    "Marker", "Highlighter", "Pencil", "Eraser", "Sharpener", "Hole Punch", "Laminator", "Paper Shredder", "Whiteboard", "Cork Board",
    "Push Pin", "Thumbtack", "Brad", "Fastener", "Label", "Sticker", "Post-it Note", "Memo Pad", "Notepad", "Legal Pad",
    "Journal", "Ledger", "Day Planner", "Address Book", "Business Card", "Envelope", "Letter Opener", "Mail Sorter", "Stamp", "Ink Pad",
    "Rubber Stamp", "Seal", "Wax", "Embosser", "Correction Fluid", "Correction Tape", "Dry Erase Marker", "Whiteboard Eraser", "Chalk", "Blackboard",
    "Easel", "Flip Chart", "Podium", "Lectern", "Projector Screen", "Pointer", "Laser Pointer", "Microphone", "Speaker", "Amplifier",
    "Clipboard", "Portfolio", "Briefcase", "Messenger Bag", "Pen Holder", "Pencil Case", "Desk Organizer", "Drawer Organizer", "File Cabinet", "Bookend",
    
    // Kitchen Items
    "Stove", "Oven", "Microwave", "Refrigerator", "Dishwasher", "Blender", "Mixer", "Toaster", "Coffee Maker", "Tea Kettle",
    "Pot", "Pan", "Skillet", "Wok", "Casserole Dish", "Baking Sheet", "Cutting Board", "Knife", "Fork", "Spoon",
    "Plate", "Bowl", "Cup", "Mug", "Glass", "Wine Glass", "Champagne Flute", "Shot Glass", "Pitcher", "Serving Tray",
    "Ladle", "Spatula", "Whisk", "Tongs", "Measuring Cup", "Measuring Spoon", "Colander", "Strainer", "Grater", "Peeler",
    "Can Opener", "Bottle Opener", "Corkscrew", "Pizza Cutter", "Ice Cream Scoop", "Garlic Press", "Potato Masher", "Rolling Pin", "Pastry Brush", "Oven Mitt",
    "Potholder", "Apron", "Dish Rack", "Sponge", "Scrubber", "Dish Soap", "Paper Towel", "Napkin", "Placemat", "Tablecloth",
    "Coaster", "Trivet", "Salt Shaker", "Pepper Grinder", "Sugar Bowl", "Creamer", "Butter Dish", "Gravy Boat", "Teapot", "Coffee Pot",
    "French Press", "Espresso Machine", "Juicer", "Food Processor", "Slow Cooker", "Pressure Cooker", "Rice Cooker", "Deep Fryer", "Grill", "Griddle",
    "Muffin Tin", "Cake Pan", "Pie Plate", "Loaf Pan", "Cookie Sheet", "Cooling Rack", "Sifter", "Funnel", "Mortar", "Pestle"
];

// Make it available globally instead of using ES6 modules
window.memoryPalaceObjects = memoryPalaceObjects; 